###
POST http://localhost:8080/transactions HTTP/1.1
content-type: application/json

{
  "amount": 1.01,
  "date": "1/1/2000",
  "merchant": "Walmart",
  "category": "groceries",
  "description": "null",
  "account": 101,
  "taxRelated": true
}